# Generated by Django 2.1.4 on 2019-04-10 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contactme',
        ),
    ]
