# Generated by Django 2.1.4 on 2019-04-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contactme'),
    ]

    operations = [
        migrations.CreateModel(
            name='filec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=40)),
                ('authorname', models.CharField(default='', max_length=40)),
                ('fileupload', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='filehtml',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=40)),
                ('authorname', models.CharField(default='', max_length=40)),
                ('fileupload', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='filepython',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=40)),
                ('authorname', models.CharField(default='', max_length=40)),
                ('fileupload', models.FileField(upload_to='')),
            ],
        ),
    ]
