# Generated by Django 2.1.4 on 2019-04-13 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_tutor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='tutorname',
            new_name='username',
        ),
    ]
