# Generated by Django 2.1.4 on 2019-04-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190413_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='username',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
