# Generated by Django 2.1.4 on 2019-04-26 09:48

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashbooard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=40)),
                ('position', models.CharField(max_length=100)),
                ('recruiter', models.CharField(max_length=40)),
                ('interviewtime', models.TimeField()),
                ('jobresposibilities', ckeditor.fields.RichTextField()),
                ('interviewslot', models.DateTimeField(default='')),
                ('officelocation', models.CharField(max_length=100)),
                ('signature', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='popupuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('emailid', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=60)),
                ('dashboard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='interview_broadcast.Dashbooard')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
